config/routes.rb
Sso::Application.routes.draw do
  
  resources :employees
  resources :driver_licenses
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'
  match '/create', to: 'employees#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/driver_license.rb
class DriverLicense < ActiveRecord::Base
  attr_accessible :code, :expiration, :description
  belongs_to :employee

  validates :code, presence: true

  default_scope order: 'driver_licenses.created_at DESC'
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :address, :email, :name, :sex, :trainer, :document_type, :document_number, :driver_licenses_attributes
  has_many :driver_licenses, dependent: :destroy #con esta opcion dependent destroy, si eliminamos un empleado, se eliminan sus licencias de conducir
  accepts_nested_attributes_for :driver_licenses, :reject_if => lambda { |a| a[:code].blank? }, :allow_destroy => true


  validates :name, presence: true, length: { maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
    format: { with: VALID_EMAIL_REGEX},
    uniqueness: { case_sensitive: false }
  validates :document_type, presence: true
  validates :document_number, presence: true
  default_scope {where(status: true)}

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :email, :name, :password, :password_confirmation, :admin #ver listing 9.42

  before_save { |user| user.email = email.downcase  }
  before_save :create_remember_token

  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
            format: { with: VALID_EMAIL_REGEX}, 
            uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: {minimum: 6}
  validates :password_confirmation, presence: true

  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/driver_licenses_controller.rb
class DriverLicensesController < ApplicationController
  #before_filter :signed_in_employee
  #before_filter :admin_employee

  def create
    @driver_license = current_employee.driver_licenses.build(params[:driver_license])
    if @driver_license.save
      flash[:success] = "Licencia de Conducir Creada"
      redirect_to current_employee
    else
      render 'static_pages/home'
    end
  end

  def destroy
    driver_license=DriverLicense.find(params[:id])
    DriverLicense.find(params[:id]).destroy
    flash[:success] = "Licencia de Conducir Eliminada"
    redirect_to employee_path(driver_license.employee)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_filter :signed_in_user
  #before_filter :correct_employee
 # before_filter :admin_user
  before_filter :load

  def load
    @employees = Employee.paginate(page: params[:page])
    @employee = Employee.new
  end

  def index
    #@employees = Employee.paginate(page: params[:page])
    #respond_to do |format|
     # format.html
      #format.json { render json: EmployeesDatatable.new(view_context) }
    #end
  end

  #def show
   # @employee = Employee.find(params[:id])
    #@driver_licenses = @employee.driver_licenses.paginate(page: params[:page])
  #end

  #def new
   # @employee = Employee.new
    #1.times { @employee.driver_licenses.build}
  #end

  def create
    @employee = Employee.new(params[:employee])
    if @employee.save
      #sign_in @employee
      flash[:success] = "Nuevo Empleado Creado"
      @employees = Employee.paginate(page: params[:page])
      @employee.driver_licenses.build
     # redirect_to @employee
    #else
     # render 'new'
    end
  end

  def edit
    @employee = Employee.find(params[:id])
    1.times { @employee.driver_licenses.build}
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update_attributes(params[:employee])
      flash[:success] = "Perfil Actualizado"
      #sign_in @employee
      #redirect_to @employee
      @employees = Employee.paginate(page: params[:page])
    #else
     # render 'edit'
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    if @employee.update_attribute(:status,false)
      flash[:success] = "Empleado dado de baja"
      #redirect_back_or employees_path
      @employees = Employee.paginate(page: params[:page])
    #else
     # render 'index'
    end
  end

  #METODOS PRIVADOS
  private
    def correct_employee
      @employee = Employee.find(params[:id])
      redirect_to(root_path) unless current_user?(@employee)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if signed_in?
      redirect_to employees_path
    end
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or employees_path
    else
      #flash.now hace que el mensaje no persista en subsecuentes paginas listing 8.12
      flash.now[:error] = 'Combinacion de email y password erroneo'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_filter :signed_in_user
  before_filter :admin_user

  def show
    @user = User.find(params[:id])
  end

  def index
    @user = User.all
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      #sign_in @employee
      flash[:success] = "Nuevo Empleado Creado"
      redirect_to @employee
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #Si no encuentra un subtitulo agrega
  #uno por defecto
  def full_title (page_title)
    base_title = "SSO Manager"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
  #Returns the Gravatar (http://gravatar.com/) for the given employee
  def gravatar_for(employee, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(employee.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, alt: employee.name, class: "gravatar")
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in?
    !current_user.nil?
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Debe ser administrador" 
    end
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.original_url
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

  def admin_user?(user)
    current_user.admin?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/driver_licenses/_driver_license.html.erb
<li>
<span class="content">categoria: <%= driver_license.code %> | <%= driver_license.description %><br /> vencimiento: <%= driver_license.expiration %></span>
  <span class="timestamp">
    Obtenida hace <%= time_ago_in_words(driver_license.created_at) %>
  </span>
    <%= link_to "Eliminar", driver_license, method: :delete,
                                     confirm: "¿Esta Seguro?",
                                     title: driver_license.code %>
</li>

app/views/employees/_employee.html.erb
<% if employee.status? %>
      <tr>
        <td> <%= gravatar_for employee, size: 32 %></td>
        <td><%= link_to employee.name, employee %></td>
        <td><%= employee.address %></td>
        <td><%= employee.document_type %></td>
        <td><%= employee.document_number %></td>
        <td><%= employee.created_at.strftime("%B %e, %Y") %></td>
        <td>
          | <%= link_to "X", employee, remote: true, method: :delete, confirm: "¿Esta seguro?" %>
          | <%= link_to "Editar", edit_employee_path(employee), remote: true %>
        </td>
      </tr>
<% end %>

app/views/employees/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.text_field :name, placeholder: "Nombre Completo" %>
<%= f.text_field :email, placeholder: "Email" %>

<%= f.text_field :document_type, placeholder: "Tipo de Dcomuento" %>

<%= f.text_field :document_number, placeholder: "Numero de Documento" %>

<%= f.text_field :sex, placeholder: "Genero" %>

app/views/employees/_new.html.erb
<% provide(:title, 'Alta Empleado') %>
<h1>Alta Empleado </h1>
<div class="row">
  <aside class="span4">
    <section>
    </section>
  </aside>
  <div class="span6 offset3">
    <%= form_for(@employee, :remote => true) do |f| %>
      <div class"input-group input-lg">
        <%= render 'fields', f: f %>
        <%= render 'shared/driver_license_form', f: f %>
        <%= f.submit "Crear Empleado", class: "btn btn-large btn-primary" %>
      </div>
    <% end %> 
  </div>
</div>

app/views/employees/create.js.erb
<% if @employees.errors.any? -%>
  /*Hide the flash notice div*/
  $("#flash_notice").hide(300);

  /*Update the html of the div employee_errors with the new one*/
  $("#employee_errors").html("<%= escape_javascript(error_messages_for(@employee))%>");

  /*Show the div employee_errors*/
  $("#employee_errors").show(300);
<% else -%>
  /*Hide the div employee_errors*/
  $("#employee_errors").hide(300);

  /*Update the html of the div flash_notice with the new one*/
  $("#flash_notice").html("<%= escape_javascript(flash[:notice])%>");

  /*Show the flash_notice div*/
  $("#flash_notice").show(300);

  /*Clear the entire form*/
  $(":input:not(input[type=submit])").val("");

  /*Replace the html of the div post_lists with the updated new one*/
  $("#employees_list").html("<%= escape_javascript( render(partial: @employees) ) %>");
<% end -%>

app/views/employees/destroy.js.erb
$("#employee_errors").hide(300);
$("#flash_notice").html("<%= escape_javascript(flash[:notice])%>");
$("#flash_notice").show(300);
$("#employees_list").html("<%= escape_javascript( render(partial: @employees) ) %>");

app/views/employees/edit.html.erb
<% provide(:title, 'Editar Empleado') %>
<h1>Editar Empleado </h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@employee) do |f| %>
      <%= render 'fields', f: f %>
      <%= render 'shared/driver_license_form', f: f %>
      <%= f.submit "Guardar Cambios", class: "btn btn-large btn-primary" %>
    <% end %> 

    <%= gravatar_for @employee %>
    <a href="http://gravatar.com/emails">Cambiar</a>
  </div>
</div>

app/views/employees/edit.js.erb
$("#employee_form").html("<%= escape_javascript(render(:partial => "new"))%>");

app/views/employees/index.html.erb
<% provide(:title, 'Todos los Empleados') %>
<h1>Todos los Empleados</h1>

<%= will_paginate %>

<table id="employees" class="display" data-source="<%= employees_url(format: "json") %>">
  <thead>
    <tr>
      <th>Imagen</th>
      <th>Nombre</th>
      <th>Domicilio</th>
      <th>Tipo de Documento</th>
      <th>Numero de Documento</th>
      <th>Fecha de Creación</th>
      <th>Opciones</th>
    </tr>
  </thead>
<!- 9.3.4 Partial Render ->
<tbody>
  <div id="employees_list"> <%= render @employees %></div>
</tbody>
</table>
<div id="employee_form"><%= render 'new' %></div>
<%= will_paginate %>

app/views/employees/show.html.erb
<% provide(:title, @employee.name) %>
<div class="row">
  <aside class="span8">
    <section>
      <h1>
        <%= gravatar_for @employee %>
        <%= @employee.name %>
      | <%= link_to "Editar", edit_employee_path(@employee) %>
      </h1>
    </section>
      <span class="content">
        <p>Direccion: <%= @employee.address %></p></span>
      <span> <p>Email: <%= @employee.email %></p></span>
        <p>Tipo de Documento: <%= @employee.document_type %>  
        <%= @employee.document_number %></p>
        <p>Estado: <%= @employee.status %></p>
        <p>Entrenador: <%= @employee.trainer %></p>
      </span>
  </aside>

  <div class="span4">
    <% if @employee.driver_licenses.any? %>
      <h3>Licencias de Conducir (<%= @employee.driver_licenses.count %>)</h3>
      <ol class="driver_licenses">
          <%= render @driver_licenses %>
        </ol>
      <%= will_paginate @driver_licenses %>
    <% end %>
  </div>
</div>

app/views/employees/update.js.erb
<% if @employee.errors.any? -%>
  $("#flash_notice").hide(300);
  $("#employee_errors").html("<%= escape_javascript(error_messages_for(@employee))%>");
  $("#employee_errors").show(300);
<% else -%>
  $("#employee_errors").hide(300);
  $("#flash_notice").html("<%= escape_javascript(flash[:notice])%>");
  $("#flash_notice").show(300);
  $(":input:not(input[type=submit])").val("");
  $("#employees_list").html("<%= escape_javascript( render(:partial => "employees") ) %>");
<% end -%>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://sso.com.ar/">SSO stuff Test</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Ayuda", help_path %></li>
      <li><%= link_to "Contacto", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
<div class="navbar-inner">
  <div class="container">
    <%= link_to "SSO Manager", root_path, id: "logo" %>
    <nav>
    <ul class="nav pull-right">
      <li><%= link_to "Inicio", root_path %></li>
      <li></li>
      <% if signed_in? %>
        <li id="fat-menu" class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Personal <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Listar", employees_path %></li>
            <li><%= link_to "Alta", create_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Diagrama Trabajo", "#" %></li>
          </ul>
        </li>
        <li id="fat-menu" class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Cuenta <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li class="divider"></li>
            <li><%= link_to "Salir", signout_path, method: "delete" %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Ingresar", signin_path %></li>
      <% end %>
    </ul>
    </nav>
  </div>
</div>
</header>

app/views/layouts/_shim.html.erb
 <!--[if lt IE 9]>
 <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
 <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= full_title(yield(:title)) %> </title> 
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
 
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    <%# javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js' %>
<%= javascript_include_tag 'rails' %>
    <%= render 'layouts/footer' %>
    <br /><br />
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/shared/_driver_license_form.html.erb
<%= render 'shared/error_messages', object: f.object %>
<%= f.fields_for :driver_licenses, remote: true do |b| %>
  <h3>Licencia de Conducir</h3>
  <div class="driver_licenses">
    <%= b.text_field :code, placeholder: "Categoria"  %>
    <%= b.text_field :description, placeholder: "Descripcion"  %>
    <%= b.label :expiration, 'Fecha Vencimiento'  %>
    <%= b.date_select :expiration %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>                                                                       
  <div id="error_expanation">                                                                     
    <div class="alert alert-error">                                                               
      The form contains <%= pluralize(object.errors.count, "error") %>                            
    </div>                                                                                        
    <ul>                                                                                          
      <% object.errors.full_messages.each do |msg| %>                                             
        <li>* <%= msg %></li>                                                                     
      <% end %>                                                                                   
    </ul>                                                                                         
  </div>                                                                                          
<% end %>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Inicio') %>
  <div class="center hero-unit">
    <h1>Inicio</h1>
    <h2>
      SSO Manager
      <a href="#">Software de Gestion Industrial</a>
      2013.
    </h2>

    <% if !signed_in? %>
      <%= link_to "Ingresar", signin_path, class: "btn btn-large btn-primary" %>
    <% end %>  
  </div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>